import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Banner from './../comonents/Home/Banner/Banner';
import HomeFetaures from './../comonents/Home/HomeFetaures.js/HomeFetaures';
import HomeClippingPathService from './../comonents/Home/HomeClippingPathService/HomeClippingPathService';
import HomeEditingProcess from './../comonents/Home/HomeEditingProcess/HomeEditingProcess';
import HomePrice from './../comonents/Home/HomePrice/HomePrice';
import RecentPost from './../comonents/RecentPost/RecentPost';
import HomeResult from './../comonents/Home/HomeResult/HomeResult';
import HomeGrowYourBuisness from './../comonents/Home/HomeGrowYourBuisness/HomeGrowYourBuisness';
import HomeBenefits from './../comonents/Home/HomeBenefits/HomeBenefits';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.mainf}>
        <Banner />       
        <HomeFetaures />
        <HomeClippingPathService />
        <HomeEditingProcess />
        <HomePrice />
        <HomeResult />
        <HomeBenefits />
        <HomeGrowYourBuisness />
        <RecentPost />
      </main>
    </div>
  )
}
